<?php
/**
 * FoxDesk - Configuration
 * Generated by installer on 2026-08-12 18:26:36
 */

// Database Configuration
define('DB_HOST', '127.0.0.1');
define('DB_PORT', '13306');
define('DB_NAME', 'foxdesk');
define('DB_USER', 'foxdesk');
define('DB_PASS', 'foxpass');

// Security
define('SECRET_KEY', 'c09fd0122c70e032c471e6b493dab94807d9bd560a1e9814eaa09775d6848a9d');

// Application Settings
define('APP_NAME', 'FoxDesk Test');
define('APP_URL', 'http://127.0.0.1:8091');

// Upload Settings
define('UPLOAD_DIR', 'uploads/');
define('MAX_UPLOAD_SIZE', 10 * 1024 * 1024); // 10MB

// Timezone
date_default_timezone_set('Europe/Prague');
