<?php
$page='admin';$page_title=t('Initiative approval rules');$user=current_user();ensure_initiative_tables();
if(!initiative_can('initiatives.manage_settings')){header('Location: index.php?page=work');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){require_csrf_token();try{initiative_admin_save_approval_rule($_POST);flash(t('Approval rule saved.'),'success');}catch(Throwable $e){flash($e->getMessage(),'error');}header('Location: '.url('admin',['section'=>'initiative-approvals']));exit;}
$ref=initiative_reference_data();$rules=db_fetch_all('SELECT r.*,t.name type_name,a.name area_name,CONCAT(u.first_name," ",u.last_name) approver_name FROM initiative_approval_rules r LEFT JOIN initiative_types t ON t.id=r.initiative_type_id LEFT JOIN initiative_org_units a ON a.id=r.area_id LEFT JOIN users u ON u.id=r.approver_user_id ORDER BY r.priority,r.step_order,r.id');
require_once BASE_PATH.'/includes/header.php';
?>
<section class="fd-page-section max-w-6xl mx-auto"><div class="mb-4"><h1 class="text-2xl font-bold text-theme-primary"><?php echo e(t('Initiative approval rules'));?></h1><p class="text-sm text-theme-muted"><?php echo e(t('Route approvals by type, area and forecast investment.'));?></p></div><?php require BASE_PATH.'/includes/components/admin-nav.php';?>
 <div class="fd-card p-5 my-4"><h2 class="font-semibold text-theme-primary mb-3"><?php echo e(t('New approval rule'));?></h2><form method="post" class="grid grid-cols-1 md:grid-cols-3 gap-3"><?php echo csrf_field();?><input required class="fd-input" name="name" placeholder="<?php echo e(t('Name'));?>"><select class="fd-select" name="initiative_type_id"><option value=""><?php echo e(t('All types'));?></option><?php foreach($ref['types'] as $option):?><option value="<?php echo (int)$option['id'];?>"><?php echo e($option['name']);?></option><?php endforeach;?></select><select class="fd-select" name="area_id"><option value=""><?php echo e(t('All areas'));?></option><?php foreach($ref['areas'] as $option):?><option value="<?php echo (int)$option['id'];?>"><?php echo e($option['name']);?></option><?php endforeach;?></select><input type="number" min="0" step="0.01" class="fd-input" name="minimum_investment" placeholder="<?php echo e(t('Minimum investment'));?>"><input type="number" min="0" step="0.01" class="fd-input" name="maximum_investment" placeholder="<?php echo e(t('Maximum investment'));?>"><select class="fd-select" name="approver_user_id"><option value=""><?php echo e(t('Role-based / unassigned'));?></option><?php foreach($ref['users'] as $option):?><option value="<?php echo (int)$option['id'];?>"><?php echo e(trim($option['first_name'].' '.$option['last_name']));?></option><?php endforeach;?></select><input class="fd-input" name="approver_role" placeholder="<?php echo e(t('Approver role'));?>"><input type="number" class="fd-input" name="priority" value="0" placeholder="<?php echo e(t('Priority'));?>"><input type="number" min="0" class="fd-input" name="step_order" value="0" placeholder="<?php echo e(t('Step order'));?>"><label class="text-sm flex items-center gap-2"><input type="checkbox" name="is_active" value="1" checked><?php echo e(t('Active'));?></label><button class="fd-button fd-button--primary md:col-span-2"><?php echo e(t('Save rule'));?></button></form></div>
 <div class="fd-card overflow-x-auto"><table class="fd-table w-full"><thead><tr><th><?php echo e(t('Rule'));?></th><th><?php echo e(t('Conditions'));?></th><th><?php echo e(t('Approver'));?></th><th><?php echo e(t('Order'));?></th></tr></thead><tbody><?php foreach($rules as $rule):?><tr><td><?php echo e($rule['name']);?></td><td class="text-sm"><?php echo e(($rule['type_name']?:t('All types')).' · '.($rule['area_name']?:t('All areas')).' · '.($rule['minimum_investment']??0).'–'.($rule['maximum_investment']??'∞'));?></td><td><?php echo e($rule['approver_name']?:($rule['approver_role']?:t('Unassigned')));?></td><td><?php echo (int)$rule['step_order'];?></td></tr><?php endforeach;?></tbody></table></div>
</section>
<?php require_once BASE_PATH.'/includes/footer.php';?>
