<?php
$page='initiative';$id=(int)($_GET['id']??$_POST['id']??0);$user=current_user();$initiative=initiative_get($id);
if(!$initiative||!initiative_can('initiatives.view',$initiative,$user)){flash(t('Initiative not found.'),'warning');header('Location: index.php?page=initiatives');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 require_csrf_token();$action=(string)($_POST['initiative_action']??'');
 try{
  if($action==='transition')initiative_transition($id,(int)$_POST['to_status_id'],trim((string)($_POST['justification']??'')),$user);
  elseif($action==='add_cost')initiative_add_cost($id,$_POST,$user);
  elseif($action==='add_benefit')initiative_add_benefit($id,$_POST,$user);
  elseif($action==='link_ticket')initiative_link_ticket($id,(int)$_POST['ticket_id'],$user);
  elseif($action==='measure')initiative_record_measurement($id,$_POST,$user);
  elseif($action==='triage')initiative_record_triage($id,(string)$_POST['decision'],trim((string)($_POST['notes']??'')),initiative_nullable_id($_POST['owner_id']??0),$user);
  elseif($action==='rollout')initiative_add_rollout($id,$_POST,$user);
  elseif($action==='approval')initiative_decide_approval((int)$_POST['approval_id'],(string)$_POST['decision'],trim((string)($_POST['comments']??'')),$user);
  elseif($action==='request_approval')initiative_add_approval($id,(int)$_POST['approver_id'],trim((string)($_POST['approver_role']??'')),(int)($_POST['step_order']??0));
  elseif($action==='evaluate')initiative_submit_evaluation($id,(int)$_POST['committee_id'],(array)($_POST['scores']??[]),trim((string)($_POST['comments']??'')),!empty($_POST['conflict_declared']),trim((string)($_POST['conflict_reason']??'')),$user);
  elseif($action==='homologate')initiative_homologate($id,(string)$_POST['decision'],trim((string)($_POST['notes']??'')),$user);
  else throw new InvalidArgumentException('Invalid action.');
  flash(t('Initiative updated.'),'success');header('Location: '.url('initiative',['id'=>$id]));exit;
 }catch(Throwable $e){flash($e->getMessage(),'error');header('Location: '.url('initiative',['id'=>$id]));exit;}
}
$model=initiative_detail_model($id);$initiative=$model['initiative'];$ref=initiative_reference_data();$page_title=$initiative['name'];$currency=initiative_financial_setting('currency','BRL');
$money=static fn($v)=>$currency.' '.number_format((float)$v,2,',','.');$pct=static fn($v)=>$v===null?'—':number_format((float)$v,1,',','.').'%';
require_once BASE_PATH.'/includes/header.php';
?>
<section class="fd-page-section max-w-7xl mx-auto" data-initiative-detail>
 <div class="fd-card p-5 mb-4">
  <div class="flex flex-wrap justify-between gap-4"><div><div class="flex items-center gap-2 mb-1"><span class="text-xs text-theme-muted"><?php echo e($initiative['code']);?></span><span class="fd-badge" style="--badge-color:<?php echo e($initiative['status_color']);?>"><?php echo e(t($initiative['status_name']));?></span></div><h1 class="text-2xl font-bold text-theme-primary"><?php echo e($initiative['name']);?></h1><p class="text-sm text-theme-muted mt-1"><?php echo e($initiative['summary']?:t('No summary provided.'));?></p></div><div class="flex items-start gap-2"><?php if(initiative_can_edit($initiative,$user)):?><a class="fd-button fd-button--secondary" href="<?php echo e(url('initiative-form',['id'=>$id]));?>"><?php echo e(t('Edit'));?></a><?php endif;?><a class="fd-button fd-button--secondary" href="<?php echo e(url('initiatives'));?>"><?php echo e(t('Portfolio'));?></a></div></div>
  <dl class="grid grid-cols-2 md:grid-cols-5 gap-3 mt-5 text-sm"><?php foreach([[t('Type'),$initiative['type_name']],[t('Area'),$initiative['area_name']],[t('Unit'),$initiative['unit_name']],[t('Owner'),$initiative['owner_name']],[t('Sponsor'),$initiative['sponsor_name']]] as $info):?><div><dt class="text-xs text-theme-muted"><?php echo e($info[0]);?></dt><dd class="font-medium text-theme-primary"><?php echo e($info[1]?:'—');?></dd></div><?php endforeach;?></dl>
 </div>
 <?php if($model['transitions']):?><div class="fd-card p-4 mb-4"><h2 class="font-semibold text-theme-primary mb-3"><?php echo e(t('Workflow actions'));?></h2><div class="flex flex-wrap gap-2"><?php foreach($model['transitions'] as $transition):?><form method="post" class="flex gap-2"><?php echo csrf_field();?><input type="hidden" name="id" value="<?php echo $id;?>"><input type="hidden" name="initiative_action" value="transition"><input type="hidden" name="to_status_id" value="<?php echo (int)$transition['to_status_id'];?>"><?php if(!empty($transition['requires_justification'])):?><input required class="fd-input" name="justification" placeholder="<?php echo e(t('Justification'));?>"><?php endif;?><button class="fd-button fd-button--secondary" type="submit"><?php echo e(t($transition['to_name']));?></button></form><?php endforeach;?></div></div><?php endif;?>
 <div class="grid grid-cols-1 xl:grid-cols-3 gap-4">
  <div class="xl:col-span-2 space-y-4">
   <div class="fd-card p-5"><h2 class="font-semibold text-theme-primary mb-3"><?php echo e(t('Business context'));?></h2><div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm"><?php foreach([[t('Current problem'),$initiative['problem_statement']],[t('Opportunity'),$initiative['opportunity']],[t('Proposed solution'),$initiative['proposed_solution']],[t('Objective'),$initiative['objective']],[t('Risks'),$initiative['risks']],[t('Dependencies'),$initiative['dependencies']]] as $block):?><div><h3 class="text-xs font-semibold uppercase text-theme-muted mb-1"><?php echo e($block[0]);?></h3><p class="text-theme-secondary whitespace-pre-line"><?php echo e($block[1]?:'—');?></p></div><?php endforeach;?></div></div>
   <?php if($initiative['status_group']==='triage'&&initiative_can('initiatives.triage',$initiative,$user)):?><div class="fd-card p-5"><h2 class="font-semibold text-theme-primary mb-3"><?php echo e(t('Structured triage'));?></h2><form method="post" class="grid grid-cols-1 md:grid-cols-2 gap-3"><?php echo csrf_field();?><input type="hidden" name="id" value="<?php echo $id;?>"><input type="hidden" name="initiative_action" value="triage"><select class="fd-select" name="decision"><option value="proceed"><?php echo e(t('Proceed'));?></option><option value="duplicate"><?php echo e(t('Duplicate'));?></option><option value="merge"><?php echo e(t('Merge'));?></option><option value="return_for_information"><?php echo e(t('Return for information'));?></option><option value="reject"><?php echo e(t('Reject'));?></option></select><select class="fd-select" name="owner_id"><option value=""><?php echo e(t('Keep current owner'));?></option><?php foreach($ref['users'] as $option):?><option value="<?php echo (int)$option['id'];?>"><?php echo e(trim($option['first_name'].' '.$option['last_name']));?></option><?php endforeach;?></select><textarea required class="fd-input md:col-span-2" name="notes" placeholder="<?php echo e(t('Triage findings and justification'));?>"></textarea><button class="fd-button fd-button--primary md:col-span-2"><?php echo e(t('Save triage'));?></button></form></div><?php endif;?>
   <div class="fd-card p-5"><div class="flex items-center justify-between mb-3"><h2 class="font-semibold text-theme-primary"><?php echo e(t('Forecast × validated × actual'));?></h2></div><div class="overflow-x-auto"><table class="fd-table w-full"><thead><tr><th><?php echo e(t('Scenario'));?></th><th class="text-right"><?php echo e(t('Investment'));?></th><th class="text-right"><?php echo e(t('Annual benefit'));?></th><th class="text-right"><?php echo e(t('ROI'));?></th><th class="text-right"><?php echo e(t('Payback'));?></th><th class="text-right"><?php echo e(t('NPV'));?></th></tr></thead><tbody><?php foreach(['forecast'=>t('Forecast'),'validated'=>t('Validated'),'actual'=>t('Actual')] as $key=>$label):$f=$model['financials'][$key]??[];?><tr><td class="font-medium"><?php echo e($label);?></td><td class="text-right"><?php echo e($money($f['investment']??0));?></td><td class="text-right"><?php echo e($money($f['benefit_annual']??0));?></td><td class="text-right"><?php echo e($pct($f['roi_percent']??null));?></td><td class="text-right"><?php echo ($f['payback_months']??null)===null?'—':e(number_format((float)$f['payback_months'],1,',','.').' '.t('months'));?></td><td class="text-right"><?php echo e($money($f['npv']??0));?></td></tr><?php endforeach;?></tbody></table></div>
    <?php if(initiative_can_edit($initiative,$user)||initiative_can('initiatives.finance_validate',$initiative,$user)):?><div class="grid grid-cols-1 lg:grid-cols-2 gap-4 mt-4 pt-4 border-t">
     <form method="post" class="space-y-2"><?php echo csrf_field();?><input type="hidden" name="id" value="<?php echo $id;?>"><input type="hidden" name="initiative_action" value="add_cost"><h3 class="text-sm font-semibold text-theme-primary"><?php echo e(t('Add cost'));?></h3><div class="grid grid-cols-2 gap-2"><select class="fd-select" name="scenario"><option value="forecast"><?php echo e(t('Forecast'));?></option><option value="validated"><?php echo e(t('Validated'));?></option><option value="actual"><?php echo e(t('Actual'));?></option></select><input required class="fd-input" name="category" placeholder="<?php echo e(t('Category'));?>"><input required type="number" min="0" step="0.01" class="fd-input" name="amount" placeholder="0.00"><select class="fd-select" name="periodicity"><option value="one_time"><?php echo e(t('One time'));?></option><option value="monthly"><?php echo e(t('Monthly'));?></option><option value="annual"><?php echo e(t('Annual'));?></option></select><input class="fd-input col-span-2" name="description" placeholder="<?php echo e(t('Description'));?>"></div><button class="fd-button fd-button--secondary fd-button--sm" type="submit"><?php echo e(t('Add cost'));?></button></form>
     <form method="post" class="space-y-2"><?php echo csrf_field();?><input type="hidden" name="id" value="<?php echo $id;?>"><input type="hidden" name="initiative_action" value="add_benefit"><h3 class="text-sm font-semibold text-theme-primary"><?php echo e(t('Add benefit'));?></h3><div class="grid grid-cols-2 gap-2"><select class="fd-select" name="scenario"><option value="forecast"><?php echo e(t('Forecast'));?></option><option value="validated"><?php echo e(t('Validated'));?></option><option value="actual"><?php echo e(t('Actual'));?></option></select><select class="fd-select" name="benefit_type"><option value="hours_saved"><?php echo e(t('Hours saved'));?></option><option value="direct_cost"><?php echo e(t('Direct cost reduction'));?></option><option value="revenue"><?php echo e(t('Revenue increase'));?></option><option value="loss_reduction"><?php echo e(t('Loss reduction'));?></option><option value="risk_reduction"><?php echo e(t('Risk reduction'));?></option><option value="non_financial"><?php echo e(t('Non-financial'));?></option></select><input type="number" min="0" step="0.01" class="fd-input" name="amount" placeholder="0.00"><select class="fd-select" name="periodicity"><option value="annual"><?php echo e(t('Annual'));?></option><option value="monthly"><?php echo e(t('Monthly'));?></option><option value="one_time"><?php echo e(t('One time'));?></option></select><input class="fd-input col-span-2" name="description" placeholder="<?php echo e(t('Description'));?>"></div><button class="fd-button fd-button--secondary fd-button--sm" type="submit"><?php echo e(t('Add benefit'));?></button></form>
    </div><?php endif;?>
   </div>
   <div class="fd-card p-5"><div class="flex justify-between gap-3"><h2 class="font-semibold text-theme-primary"><?php echo e(t('Execution tickets'));?></h2><span class="text-sm text-theme-muted"><?php echo e(number_format($model['ticket_actuals']['hours'],1,',','.').' h · '.$money($model['ticket_actuals']['cost']));?></span></div><?php if(!$model['tickets']):?><p class="text-sm text-theme-muted py-4"><?php echo e(t('No linked tickets.'));?></p><?php else:?><div class="overflow-x-auto mt-3"><table class="fd-table w-full"><tbody><?php foreach($model['tickets'] as $ticket):?><tr><td><a class="font-medium hover:underline" href="<?php echo e(url('ticket',['t'=>$ticket['hash']]));?>">#<?php echo (int)$ticket['id'];?> <?php echo e($ticket['title']);?></a></td><td><?php echo e($ticket['status_name']?:'—');?></td><td><?php echo e($ticket['assignee_name']?:'—');?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?><?php if(initiative_can('initiatives.manage_execution',$initiative,$user)):?><form method="post" class="flex gap-2 mt-3"><?php echo csrf_field();?><input type="hidden" name="id" value="<?php echo $id;?>"><input type="hidden" name="initiative_action" value="link_ticket"><input required type="number" min="1" class="fd-input" name="ticket_id" placeholder="<?php echo e(t('Ticket ID'));?>"><button class="fd-button fd-button--secondary fd-button--sm"><?php echo e(t('Link ticket'));?></button></form><?php endif;?></div>
   <div class="fd-card p-5"><h2 class="font-semibold text-theme-primary mb-3"><?php echo e(t('Measurement checkpoints'));?></h2><?php if($model['measurements']):?><div class="overflow-x-auto"><table class="fd-table w-full"><thead><tr><th><?php echo e(t('Checkpoint'));?></th><th><?php echo e(t('Due'));?></th><th class="text-right"><?php echo e(t('Realized benefit'));?></th><th class="text-right"><?php echo e(t('Adoption'));?></th></tr></thead><tbody><?php foreach($model['measurements'] as $m):?><tr><td><?php echo (int)$m['checkpoint_days'];?> <?php echo e(t('days'));?></td><td><?php echo e($m['due_date']?:'—');?></td><td class="text-right"><?php echo e($money($m['benefit_realized']));?></td><td class="text-right"><?php echo $m['adoption_percent']===null?'—':e($pct($m['adoption_percent']));?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?><?php if(initiative_can('initiatives.manage_execution',$initiative,$user)):?><form method="post" class="grid grid-cols-2 md:grid-cols-4 gap-2 mt-4"><?php echo csrf_field();?><input type="hidden" name="id" value="<?php echo $id;?>"><input type="hidden" name="initiative_action" value="measure"><input required type="number" min="1" class="fd-input" name="checkpoint_days" placeholder="<?php echo e(t('Days'));?>"><input type="number" min="0" step="0.01" class="fd-input" name="benefit_realized" placeholder="<?php echo e(t('Benefit'));?>"><input type="number" min="0" max="100" step="0.1" class="fd-input" name="adoption_percent" placeholder="<?php echo e(t('Adoption %'));?>"><input type="number" min="0" step="0.1" class="fd-input" name="hours_saved" placeholder="<?php echo e(t('Hours saved'));?>"><input class="fd-input md:col-span-3" name="notes" placeholder="<?php echo e(t('Evidence and notes'));?>"><button class="fd-button fd-button--secondary"><?php echo e(t('Record'));?></button></form><?php endif;?></div>
   <div class="fd-card p-5"><h2 class="font-semibold text-theme-primary mb-3"><?php echo e(t('Replication and rollout'));?></h2><?php foreach($model['rollouts'] as $rollout):?><div class="flex justify-between gap-3 text-sm py-2 border-b"><span><?php echo e($rollout['org_unit_name']?:t('Unspecified unit'));?></span><span class="fd-badge"><?php echo e(t(ucwords(str_replace('_',' ',$rollout['rollout_status']))));?></span></div><?php endforeach;?><?php if(initiative_can('initiatives.manage_portfolio',$initiative,$user)):?><form method="post" class="grid grid-cols-1 md:grid-cols-3 gap-2 mt-3"><?php echo csrf_field();?><input type="hidden" name="id" value="<?php echo $id;?>"><input type="hidden" name="initiative_action" value="rollout"><select class="fd-select" name="org_unit_id"><option value=""><?php echo e(t('Select unit'));?></option><?php foreach(array_merge($ref['areas'],$ref['units'],$ref['cost_centers']) as $option):?><option value="<?php echo (int)$option['id'];?>"><?php echo e($option['name']);?></option><?php endforeach;?></select><select class="fd-select" name="rollout_status"><option value="planned"><?php echo e(t('Planned'));?></option><option value="in_progress"><?php echo e(t('In progress'));?></option><option value="completed"><?php echo e(t('Completed'));?></option></select><input type="date" class="fd-input" name="target_date"><button class="fd-button fd-button--secondary md:col-span-3"><?php echo e(t('Add rollout'));?></button></form><?php endif;?></div>
   </div>
   <aside class="space-y-4">
   <div class="fd-card p-5"><h2 class="font-semibold text-theme-primary mb-3"><?php echo e(t('Approvals'));?></h2><?php if(!$model['approvals']):?><p class="text-sm text-theme-muted"><?php echo e(t('No approval requests.'));?></p><?php endif;?><?php foreach($model['approvals'] as $approval):?><div class="py-3 border-b last:border-0"><div class="flex justify-between"><span class="text-sm font-medium"><?php echo e($approval['approver_name']?:$approval['approver_role']);?></span><span class="fd-badge"><?php echo e(t(ucfirst(str_replace('_',' ',$approval['decision']))));?></span></div><?php if($approval['decision']==='pending'&&((int)$approval['approver_id']===(int)$user['id']||initiative_can('initiatives.approve',$initiative,$user))):?><form method="post" class="mt-2 space-y-2"><?php echo csrf_field();?><input type="hidden" name="id" value="<?php echo $id;?>"><input type="hidden" name="initiative_action" value="approval"><input type="hidden" name="approval_id" value="<?php echo (int)$approval['id'];?>"><input class="fd-input w-full" name="comments" placeholder="<?php echo e(t('Comments'));?>"><div class="flex gap-1"><button class="fd-button fd-button--sm fd-button--primary" name="decision" value="approved"><?php echo e(t('Approve'));?></button><button class="fd-button fd-button--sm fd-button--secondary" name="decision" value="changes_requested"><?php echo e(t('Request changes'));?></button></div></form><?php endif;?></div><?php endforeach;?></div>
   <?php if(initiative_can('initiatives.approve',$initiative,$user)):?><div class="fd-card p-5"><h2 class="font-semibold text-theme-primary mb-3"><?php echo e(t('Request approval'));?></h2><form method="post" class="space-y-2"><?php echo csrf_field();?><input type="hidden" name="id" value="<?php echo $id;?>"><input type="hidden" name="initiative_action" value="request_approval"><select required class="fd-select w-full" name="approver_id"><option value=""><?php echo e(t('Select approver'));?></option><?php foreach($ref['users'] as $option):?><option value="<?php echo (int)$option['id'];?>"><?php echo e(trim($option['first_name'].' '.$option['last_name']));?></option><?php endforeach;?></select><input class="fd-input w-full" name="approver_role" placeholder="<?php echo e(t('Approval role'));?>"><input type="number" min="0" class="fd-input w-full" name="step_order" value="0"><button class="fd-button fd-button--secondary fd-button--sm"><?php echo e(t('Request'));?></button></form></div><?php endif;?>
   <?php if(!empty($model['committees'])):?><div class="fd-card p-5"><h2 class="font-semibold text-theme-primary mb-3"><?php echo e(t('Committee evaluation'));?></h2><?php foreach($model['committees'] as $committee):$summary=$committee['summary'];?><div class="mb-4 pb-4 border-b"><div class="flex justify-between gap-2"><strong class="text-sm"><?php echo e($committee['name']);?></strong><span class="text-xs text-theme-muted"><?php echo (int)$summary['count'];?>/<?php echo (int)$committee['minimum_evaluations'];?> · <?php echo $summary['average']===null?'—':e(number_format((float)$summary['average'],2,',','.'));?></span></div><?php if($summary['high_divergence']):?><p class="text-xs text-amber-600 mt-1"><?php echo e(t('High divergence among evaluators.'));?></p><?php endif;?><?php if(initiative_can('initiatives.committee_evaluate',$initiative,$user)&&!empty($committee['criteria'])):?><form method="post" class="space-y-2 mt-3"><?php echo csrf_field();?><input type="hidden" name="id" value="<?php echo $id;?>"><input type="hidden" name="initiative_action" value="evaluate"><input type="hidden" name="committee_id" value="<?php echo (int)$committee['id'];?>"><?php foreach($committee['criteria'] as $criterion):?><label class="block text-xs text-theme-secondary"><?php echo e($criterion['name']);?> · <?php echo e(t('weight'));?> <?php echo e((string)$criterion['weight']);?><?php if(!empty($criterion['options'])):?><select required class="fd-select w-full mt-1" name="scores[<?php echo (int)$criterion['id'];?>]"><option value="">—</option><?php foreach($criterion['options'] as $option):?><option value="<?php echo e((string)$option['numeric_value']);?>"><?php echo e($option['label']);?></option><?php endforeach;?></select><?php else:?><input required type="number" step="0.01" class="fd-input w-full mt-1" name="scores[<?php echo (int)$criterion['id'];?>]"><?php endif;?></label><?php endforeach;?><textarea class="fd-input w-full" name="comments" placeholder="<?php echo e(t('Comments'));?>"></textarea><label class="text-xs"><input type="checkbox" name="conflict_declared" value="1"> <?php echo e(t('Declare conflict of interest'));?></label><input class="fd-input w-full" name="conflict_reason" placeholder="<?php echo e(t('Conflict reason'));?>"><button class="fd-button fd-button--secondary fd-button--sm"><?php echo e(t('Submit evaluation'));?></button></form><?php endif;?></div><?php endforeach;?></div><?php endif;?>
   <div class="fd-card p-5"><h2 class="font-semibold text-theme-primary mb-3"><?php echo e(t('Timeline'));?></h2><div class="space-y-4"><?php foreach($model['events'] as $event):$data=json_decode((string)$event['event_data_json'],true)?:[];?><div class="text-sm"><div class="font-medium text-theme-primary"><?php echo e(t(ucwords(str_replace('_',' ',$event['event_type']))));?></div><div class="text-xs text-theme-muted"><?php echo e(($event['actor_name']?:t('System')).' · '.$event['created_at']);?></div><?php if(!empty($data['justification'])):?><p class="text-xs text-theme-secondary mt-1"><?php echo e($data['justification']);?></p><?php endif;?></div><?php endforeach;?></div></div>
  </aside>
 </div>
</section>
<?php require_once BASE_PATH.'/includes/footer.php';?>
